server:
  port: 80

spring:
  application:
    name: medical-backend

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/medtrack
    username: medtrack
    password: medtrack
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: core
