server:
  port: 80

spring:
  application:
    name: medical-backend

  datasource:
    url: jdbc:postgresql://192.168.1.135:5432/medtrack
    username: medtrack
    password: medtrack
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: core

  thymeleaf:
    enabled: true
