server:
  port: 80

spring:
  application:
    name: medical-backend

  datasource:
    url: jdbc:postgresql://192.168.1.221:5432/medtrack
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: core
